title: "arcologies: docs"
description: an interactive environment for designing 2d sound arcologies with grid and live
baseurl: /arcologies
url: https://tyleretters.github.io/arcologies
markdown: kramdown
theme: minima