title: "ecologies: docs"
tagline: an interactive environment for designing 2d sound ecologies with grid and live
baseurl: /ecologies
url: https://tyleretters.github.io/ecologies
markdown: kramdown
theme: minima